---
name: ansible-lint

on:
  pull_request:
  push:
    branches:
      - main
      - force_ci/ansible-lint/**  # For development/debugging of the workflow.

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    name: Ansible lint
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24
